namespace HR.Domain.Enums;

public enum NotificationType
{
    APPLICATION_STATUS,
    INTERVIEW_INVITE,
    JOB_ALERT,
    CHAT_MESSAGE,
    ASSESSMENT_INVITE,
    ASSESSMENT_RESULT,
    OFFER_RECEIVED,
    OFFER_ACCEPTED,
    OFFER_NEGOTIATING,
    OFFER_DECLINED,
    JOB_INVITATION
}
