namespace HR.Domain.Enums;

public enum RoleChangeAction
{
    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_DELETED,
    ROLE_ACTIVATED,
    ROLE_DEACTIVATED,
    PERMISSION_ASSIGNED,
    PERMISSION_REVOKED,
    PERMISSION_SCOPE_CHANGED,
    USER_ASSIGNED,
    USER_REVOKED,
    ROLE_CLONED
}
